"""
Config loader: YAML → JSON Schema validation → Pydantic → typed object.

Usage:
    from app.configs.config_loader import load_metric_config, load_framework_config

    metric = load_metric_config("backend/app/configs/metrics/bias_B1.yaml")
    framework = load_framework_config("backend/app/configs/frameworks/eu_ai_act.yaml")

Error contract:
    Both loaders raise ConfigLoadError on any failure (missing file, YAML syntax
    error, JSON Schema violation, or Pydantic validation error).  The message
    always includes the offending path and the specific violation so a non-engineer
    authoring a config file gets an actionable message, not a Python stack trace.
"""

from __future__ import annotations

import json
from pathlib import Path

import jsonschema
import yaml
from pydantic import ValidationError

from app.configs.config_models import FrameworkConfig, MetricConfig

# Schema files are generated by backend/scripts/generate_schemas.py and committed
# alongside the source.  The loader resolves them relative to this file so imports
# work regardless of the working directory.
_SCHEMA_DIR = Path(__file__).resolve().parent / "schemas"
_METRICS_DIR = Path(__file__).resolve().parent / "metrics"
_METRIC_SCHEMA_PATH = _SCHEMA_DIR / "metric_config.schema.json"
_FRAMEWORK_SCHEMA_PATH = _SCHEMA_DIR / "framework_config.schema.json"


class ConfigLoadError(Exception):
    """Raised when a config file fails to load, validate, or parse.

    Attributes:
        config_path: The path to the config file that caused the error.
        schema_path: The JSON Schema file used for validation (may be None for
            YAML-parse errors).
        detail: Human-readable explanation of the failure.
    """

    def __init__(
        self,
        config_path: Path,
        detail: str,
        schema_path: Path | None = None,
    ) -> None:
        self.config_path = config_path
        self.schema_path = schema_path
        self.detail = detail
        schema_hint = f" (schema: {schema_path})" if schema_path else ""
        super().__init__(f"Config load failed for '{config_path}'{schema_hint}: {detail}")


def _load_yaml(path: Path) -> object:
    """Read and parse a YAML file, raising ConfigLoadError on any failure."""
    if not path.exists():
        raise ConfigLoadError(path, "file not found")
    try:
        with path.open(encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
    except yaml.YAMLError as exc:
        raise ConfigLoadError(path, f"YAML parse error — {exc}") from exc
    if not isinstance(data, dict):
        raise ConfigLoadError(path, "expected a YAML mapping at the top level")
    return data


def _load_json_schema(schema_path: Path) -> dict:
    """Load a JSON Schema file, raising ConfigLoadError if it is missing."""
    if not schema_path.exists():
        raise ConfigLoadError(
            schema_path,
            "JSON Schema file not found — run `python backend/scripts/generate_schemas.py` "
            "to regenerate it",
        )
    return json.loads(schema_path.read_text(encoding="utf-8"))


def _validate_against_schema(
    data: object,
    schema: dict,
    config_path: Path,
    schema_path: Path,
) -> None:
    """Validate data against JSON Schema, raising ConfigLoadError on failure."""
    validator_cls = jsonschema.validators.validator_for(schema)
    validator_cls.check_schema(schema)
    validator = validator_cls(schema)
    errors = sorted(validator.iter_errors(data), key=lambda e: list(e.absolute_path))
    if errors:
        # Report all violations, not just the first.
        messages = []
        for err in errors:
            location = " → ".join(str(p) for p in err.absolute_path) or "<root>"
            messages.append(f"  [{location}] {err.message}")
        detail = "JSON Schema validation failed:\n" + "\n".join(messages)
        raise ConfigLoadError(config_path, detail, schema_path=schema_path)


def load_metric_config(path: str | Path) -> MetricConfig:
    """Load and validate a metric YAML config file.

    Pipeline: YAML parse → JSON Schema validation → Pydantic parse → MetricConfig.

    Args:
        path: Path to the metric YAML file.

    Returns:
        A fully validated MetricConfig instance.

    Raises:
        ConfigLoadError: On any failure at any stage of the pipeline.
    """
    config_path = Path(path)
    schema = _load_json_schema(_METRIC_SCHEMA_PATH)
    data = _load_yaml(config_path)
    _validate_against_schema(data, schema, config_path, _METRIC_SCHEMA_PATH)
    try:
        return MetricConfig.model_validate(data)
    except ValidationError as exc:
        # JSON Schema passed but Pydantic caught something finer-grained (e.g. a
        # cross-field constraint).  Surface the Pydantic errors clearly.
        messages = [
            f"  [{' -> '.join(str(location) for location in error['loc'])}] {error['msg']}"
            for error in exc.errors()
        ]
        raise ConfigLoadError(
            config_path,
            "Pydantic validation failed after schema check:\n" + "\n".join(messages),
            schema_path=_METRIC_SCHEMA_PATH,
        ) from exc


def load_metric_configs_from_dir(directory: str | Path | None = None) -> list[MetricConfig]:
    """Load every metric YAML config in a directory in deterministic order."""
    config_dir = Path(directory) if directory is not None else _METRICS_DIR
    metric_paths = sorted(config_dir.glob("*.yaml"))
    return [load_metric_config(path) for path in metric_paths]


def load_framework_config(path: str | Path) -> FrameworkConfig:
    """Load and validate a framework YAML config file.

    Pipeline: YAML parse → JSON Schema validation → Pydantic parse → FrameworkConfig.

    Args:
        path: Path to the framework YAML file.

    Returns:
        A fully validated FrameworkConfig instance.

    Raises:
        ConfigLoadError: On any failure at any stage of the pipeline.
    """
    config_path = Path(path)
    schema = _load_json_schema(_FRAMEWORK_SCHEMA_PATH)
    data = _load_yaml(config_path)
    _validate_against_schema(data, schema, config_path, _FRAMEWORK_SCHEMA_PATH)
    try:
        return FrameworkConfig.model_validate(data)
    except ValidationError as exc:
        messages = [
            f"  [{' -> '.join(str(location) for location in error['loc'])}] {error['msg']}"
            for error in exc.errors()
        ]
        raise ConfigLoadError(
            config_path,
            "Pydantic validation failed after schema check:\n" + "\n".join(messages),
            schema_path=_FRAMEWORK_SCHEMA_PATH,
        ) from exc
