"""add ai system capabilities

Revision ID: 8db69212f62c
Revises: befab961259e
Create Date: 2026-06-15 09:04:42.809008
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "8db69212f62c"
down_revision: str | None = "befab961259e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_system_capabilities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("ai_system_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column(
            "capability_type",
            sa.Enum(
                "inference",
                "retrieval",
                "generation",
                "action",
                "integration",
                "other",
                name="capabilitytype",
            ),
            nullable=False,
        ),
        sa.Column("endpoint_ref", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("http_method", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("input_schema", sa.JSON(), nullable=False),
        sa.Column("output_schema", sa.JSON(), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column(
            "side_effect_level",
            sa.Enum("none", "read", "write", "destructive", name="sideeffectlevel"),
            nullable=False,
        ),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_system_id"],
            ["ai_systems.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ai_system_id", "name"),
    )
    op.create_index(
        op.f("ix_ai_system_capabilities_ai_system_id"),
        "ai_system_capabilities",
        ["ai_system_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_system_capabilities_capability_type"),
        "ai_system_capabilities",
        ["capability_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_system_capabilities_enabled"),
        "ai_system_capabilities",
        ["enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_system_capabilities_id"), "ai_system_capabilities", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_system_capabilities_name"), "ai_system_capabilities", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_ai_system_capabilities_requires_human_review"),
        "ai_system_capabilities",
        ["requires_human_review"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_system_capabilities_side_effect_level"),
        "ai_system_capabilities",
        ["side_effect_level"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ai_system_capabilities_side_effect_level"), table_name="ai_system_capabilities"
    )
    op.drop_index(
        op.f("ix_ai_system_capabilities_requires_human_review"), table_name="ai_system_capabilities"
    )
    op.drop_index(op.f("ix_ai_system_capabilities_name"), table_name="ai_system_capabilities")
    op.drop_index(op.f("ix_ai_system_capabilities_id"), table_name="ai_system_capabilities")
    op.drop_index(op.f("ix_ai_system_capabilities_enabled"), table_name="ai_system_capabilities")
    op.drop_index(
        op.f("ix_ai_system_capabilities_capability_type"), table_name="ai_system_capabilities"
    )
    op.drop_index(
        op.f("ix_ai_system_capabilities_ai_system_id"), table_name="ai_system_capabilities"
    )
    op.drop_table("ai_system_capabilities")
    sa.Enum(name="sideeffectlevel").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="capabilitytype").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
