"""add core governance models

Revision ID: befab961259e
Revises: 0001_initial_baseline
Create Date: 2026-06-11 08:17:24.219927
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'befab961259e'
down_revision: str | None = '0001_initial_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_systems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('system_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('risk_tier', sa.Enum('low', 'medium', 'high', name='risktier'), nullable=False),
    sa.Column('deployment_environment', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sa.Enum('registered', 'active', 'inactive', 'archived', name='aisystemstatus'), nullable=False),
    sa.Column('selected_frameworks', sa.JSON(), nullable=False),
    sa.Column('model_provider', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('target_endpoint_ref', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_systems_deployment_environment'), 'ai_systems', ['deployment_environment'], unique=False)
    op.create_index(op.f('ix_ai_systems_id'), 'ai_systems', ['id'], unique=False)
    op.create_index(op.f('ix_ai_systems_name'), 'ai_systems', ['name'], unique=False)
    op.create_index(op.f('ix_ai_systems_owner'), 'ai_systems', ['owner'], unique=False)
    op.create_index(op.f('ix_ai_systems_risk_tier'), 'ai_systems', ['risk_tier'], unique=False)
    op.create_index(op.f('ix_ai_systems_status'), 'ai_systems', ['status'], unique=False)
    op.create_index(op.f('ix_ai_systems_system_type'), 'ai_systems', ['system_type'], unique=False)
    op.create_table('application_context_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ai_system_id', sa.Uuid(), nullable=False),
    sa.Column('section_a', sa.JSON(), nullable=False),
    sa.Column('section_b', sa.JSON(), nullable=False),
    sa.Column('section_c', sa.JSON(), nullable=False),
    sa.Column('section_d', sa.JSON(), nullable=False),
    sa.Column('section_e', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_context_profiles_ai_system_id'), 'application_context_profiles', ['ai_system_id'], unique=True)
    op.create_index(op.f('ix_application_context_profiles_id'), 'application_context_profiles', ['id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ai_system_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('created', 'context_assembly', 'planned', 'metrics_running', 'agents_running', 'council_running', 'report_ready', 'completed', 'failed', 'degraded', 'cancelled', name='runstatus'), nullable=False),
    sa.Column('current_phase', sa.Enum('created', 'context_assembly', 'adaptive_orchestrator', 'metric_execution', 'specialist_agents', 'deliberation_council', 'action_reporting', name='runphase'), nullable=False),
    sa.Column('selected_frameworks', sa.JSON(), nullable=False),
    sa.Column('selected_metrics', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('error_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_ai_system_id'), 'evaluation_runs', ['ai_system_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_current_phase'), 'evaluation_runs', ['current_phase'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_id'), 'evaluation_runs', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_status'), 'evaluation_runs', ['status'], unique=False)
    op.create_table('audit_ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('actor_type', sa.Enum('system', 'user', 'agent', 'tool', name='ledgeractortype'), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('entry_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_ledger_entries_actor_id'), 'audit_ledger_entries', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_ledger_entries_actor_type'), 'audit_ledger_entries', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_ledger_entries_entry_hash'), 'audit_ledger_entries', ['entry_hash'], unique=False)
    op.create_index(op.f('ix_audit_ledger_entries_event_type'), 'audit_ledger_entries', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_ledger_entries_id'), 'audit_ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_audit_ledger_entries_run_id'), 'audit_ledger_entries', ['run_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tool_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('input_ref', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('output_ref', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('normalized_score', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('sensitivity', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_id'), 'evidence_records', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_records_run_id'), 'evidence_records', ['run_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_sensitivity'), 'evidence_records', ['sensitivity'], unique=False)
    op.create_index(op.f('ix_evidence_records_source_name'), 'evidence_records', ['source_name'], unique=False)
    op.create_index(op.f('ix_evidence_records_source_type'), 'evidence_records', ['source_type'], unique=False)
    op.create_index(op.f('ix_evidence_records_trace_id'), 'evidence_records', ['trace_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('finding_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='severity'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('dimension', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('framework_refs', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('recommended_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('open', 'accepted', 'mitigated', 'dismissed', name='findingstatus'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_agent_name'), 'findings', ['agent_name'], unique=False)
    op.create_index(op.f('ix_findings_dimension'), 'findings', ['dimension'], unique=False)
    op.create_index(op.f('ix_findings_finding_type'), 'findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_findings_id'), 'findings', ['id'], unique=False)
    op.create_index(op.f('ix_findings_run_id'), 'findings', ['run_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('governance_state_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('entry_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('entry_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence_number')
    )
    op.create_index(op.f('ix_governance_state_entries_entry_hash'), 'governance_state_entries', ['entry_hash'], unique=False)
    op.create_index(op.f('ix_governance_state_entries_entry_type'), 'governance_state_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_governance_state_entries_id'), 'governance_state_entries', ['id'], unique=False)
    op.create_index(op.f('ix_governance_state_entries_phase'), 'governance_state_entries', ['phase'], unique=False)
    op.create_index(op.f('ix_governance_state_entries_run_id'), 'governance_state_entries', ['run_id'], unique=False)
    op.create_index(op.f('ix_governance_state_entries_sequence_number'), 'governance_state_entries', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_governance_state_entries_source'), 'governance_state_entries', ['source'], unique=False)
    op.create_table('metric_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('dimension', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'passed', 'failed', 'error', 'skipped', name='metricresultstatus'), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('normalized_score', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_results_dimension'), 'metric_results', ['dimension'], unique=False)
    op.create_index(op.f('ix_metric_results_id'), 'metric_results', ['id'], unique=False)
    op.create_index(op.f('ix_metric_results_metric_id'), 'metric_results', ['metric_id'], unique=False)
    op.create_index(op.f('ix_metric_results_run_id'), 'metric_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_metric_results_status'), 'metric_results', ['status'], unique=False)
    op.create_index(op.f('ix_metric_results_tool_name'), 'metric_results', ['tool_name'], unique=False)
    op.create_table('verdicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('action_tier', sa.Enum('autonomous', 'supervised', 'human_review', name='actiontier'), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('synthesis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('objections', sa.JSON(), nullable=False),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('required_actions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verdicts_action_tier'), 'verdicts', ['action_tier'], unique=False)
    op.create_index(op.f('ix_verdicts_id'), 'verdicts', ['id'], unique=False)
    op.create_index(op.f('ix_verdicts_label'), 'verdicts', ['label'], unique=False)
    op.create_index(op.f('ix_verdicts_run_id'), 'verdicts', ['run_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verdicts_run_id'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_label'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_id'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_action_tier'), table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_index(op.f('ix_metric_results_tool_name'), table_name='metric_results')
    op.drop_index(op.f('ix_metric_results_status'), table_name='metric_results')
    op.drop_index(op.f('ix_metric_results_run_id'), table_name='metric_results')
    op.drop_index(op.f('ix_metric_results_metric_id'), table_name='metric_results')
    op.drop_index(op.f('ix_metric_results_id'), table_name='metric_results')
    op.drop_index(op.f('ix_metric_results_dimension'), table_name='metric_results')
    op.drop_table('metric_results')
    op.drop_index(op.f('ix_governance_state_entries_source'), table_name='governance_state_entries')
    op.drop_index(op.f('ix_governance_state_entries_sequence_number'), table_name='governance_state_entries')
    op.drop_index(op.f('ix_governance_state_entries_run_id'), table_name='governance_state_entries')
    op.drop_index(op.f('ix_governance_state_entries_phase'), table_name='governance_state_entries')
    op.drop_index(op.f('ix_governance_state_entries_id'), table_name='governance_state_entries')
    op.drop_index(op.f('ix_governance_state_entries_entry_type'), table_name='governance_state_entries')
    op.drop_index(op.f('ix_governance_state_entries_entry_hash'), table_name='governance_state_entries')
    op.drop_table('governance_state_entries')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_run_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_finding_type'), table_name='findings')
    op.drop_index(op.f('ix_findings_dimension'), table_name='findings')
    op.drop_index(op.f('ix_findings_agent_name'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_evidence_records_trace_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_source_type'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_source_name'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_sensitivity'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_run_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_audit_ledger_entries_run_id'), table_name='audit_ledger_entries')
    op.drop_index(op.f('ix_audit_ledger_entries_id'), table_name='audit_ledger_entries')
    op.drop_index(op.f('ix_audit_ledger_entries_event_type'), table_name='audit_ledger_entries')
    op.drop_index(op.f('ix_audit_ledger_entries_entry_hash'), table_name='audit_ledger_entries')
    op.drop_index(op.f('ix_audit_ledger_entries_actor_type'), table_name='audit_ledger_entries')
    op.drop_index(op.f('ix_audit_ledger_entries_actor_id'), table_name='audit_ledger_entries')
    op.drop_table('audit_ledger_entries')
    op.drop_index(op.f('ix_evaluation_runs_status'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_current_phase'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_ai_system_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index(op.f('ix_application_context_profiles_id'), table_name='application_context_profiles')
    op.drop_index(op.f('ix_application_context_profiles_ai_system_id'), table_name='application_context_profiles')
    op.drop_table('application_context_profiles')
    op.drop_index(op.f('ix_ai_systems_system_type'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_status'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_risk_tier'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_owner'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_name'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_id'), table_name='ai_systems')
    op.drop_index(op.f('ix_ai_systems_deployment_environment'), table_name='ai_systems')
    op.drop_table('ai_systems')
    # ### end Alembic commands ###
